-- 실습 10.

-- 거래 테이블에서 계좌별 누적 거래 금액을 계산 
SELECT
    TRANSACTION_ID,
    TRANSACTION_DATE,
    ACCOUNT_ID,
    SUM(AMOUNT) OVER (PARTITION BY ACCOUNT_ID ORDER BY TRANSACTION_DATE ROWS UNBOUNDED PRECEDING) CUM_AMOUNT
FROM TRANSACTIONS;

-- 각 계좌별 거래 금액의 최고 거래 금액 대비 비율을 출력하시오.
SELECT
    TRANSACTION_ID,
    ACCOUNT_ID,
    AMOUNT,
    TRUNC(AMOUNT/(MAX(AMOUNT) OVER (PARTITION BY ACCOUNT_ID)), 2) AMOUNT_RATIO
FROM TRANSACTIONS;

-- 대출 테이블에서 지점별 누적 대출 금액을 계산
SELECT
    LOAN_ID,
    LOAN_DATE,
    BRANCH_ID,
    AMOUNT,
    SUM(AMOUNT) OVER (PARTITION BY BRANCH_ID ORDER BY LOAN_DATE ROWS UNBOUNDED PRECEDING) CUM_AMOUNT
FROM LOANS;

-- 계좌 테이블에서 고객별 평균 잔액을 계산(반올림하여 소수점 둘째 자리까지 출력)
SELECT
    ACCOUNT_ID,
    CUSTOMER_ID,
    BALANCE,
    ROUND(AVG(BALANCE) OVER (PARTITION BY CUSTOMER_ID), 2) AVG_BALANCE
FROM ACCOUNTS;
