-------------실습-------------------
ALTER SESSION SET STATISTI

--1. NUMBER 형을 문자열 비교로 인해 인덱스를 못타는 문제를 NUMBER 형 연산으로 튜닝
-- 튜닝 전
SELECT * FROM EMPLOYEES
WHERE EMP_NO LIKE '101%'
OR EMP_NO LIKE '103%';

-- 튜닝 후
SELECT * FROM EMPLOYEES
WHERE (EMP_NO BETWEEN 10100 AND 10199)
OR (EMP_NO BETWEEN 10300 AND 10399);


--2. SELECT 컬럼에 NVL 함수로 인해 인덱스를 못타던 문제를 NVL 제거를 통해 해결
-- 튜닝 전
SELECT NVL(GENDER, 'NON') AS GENDER, COUNT(*)
FROM EMPLOYEES
GROUP BY NVL(GENDER, 'NON');

-- 튜닝 후
SELECT
    /*+INDEX(EMPLOYEES IDX_GENDER)*/
    GENDER,
    COUNT(*)
FROM EMPLOYEES
GROUP BY GENDER;


--3. 인덱스 컬럼의 가공으로 인해 인덱스 타지 못하는 문제를 해결
-- 튜닝 전
SELECT * FROM EMPLOYEES
WHERE GENDER || ' ' || LAST_NAME = 'M Radwan';

-- 튜닝 후
SELECT * FROM EMPLOYEES
WHERE GENDER = 'M'
AND LAST_NAME = 'Radwan';


--4. 인덱스 컬럼의 가공으로 인해 인덱스 타지 못하는 문제를 해결
-- 튜닝 전
SELECT FIRST_NAME, LAST_NAME, EMP_NO
FROM EMPLOYEES
WHERE SUBSTR(EMP_NO, 1, 4) = 1030;

-- 튜닝 후
SELECT FIRST_NAME, LAST_NAME, EMP_NO
FROM EMPLOYEES
WHERE EMP_NO BETWEEN 10300 AND 10309;

--5. 불필요한 DISTINCT로 인해 HASH_UNIQUE 발생 문제를 해결
-- 튜닝 전
SELECT DISTINCT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM EMPLOYEES E, DEPT_MANAGER D
WHERE E.EMP_NO = D.EMP_NO;

-- 튜닝 후
SELECT E.EMP_NO, E.FIRST_NAME, E.LAST_NAME, D.DEPT_NO
FROM DEPT_MANAGER D, EMPLOYEES E
WHERE  E.EMP_NO = D.EMP_NO;


--6. EXIST 구문으로 SEMI JOIN 최적화
-- 튜닝 전
SELECT COUNT(DISTINCT E.EMP_NO) AS CNT
FROM EMPLOYEES E, (
    SELECT EMP_NO
    FROM SALARIES
    WHERE SALARY > 50000
) S
WHERE E.EMP_NO = S.EMP_NO;


-- 튜닝 후
SELECT COUNT(E.EMP_NO) AS CNT
FROM EMPLOYEES E
WHERE EXISTS (
    SELECT 1
    FROM SALARIES S
    WHERE S.EMP_NO = E.EMP_NO
    AND S.SALARY > 50000
);

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));
