-- 승인된 대출(APPROVED)의 총 대출 금액과 해당 대출 건수를 출력
SELECT SUM(AMOUNT)AS TOTAL_AMOUNT, COUNT(LOAN_ID) AS NUMBER_OF_APPROVED_LOAN
FROM LOANS
WHERE STATUS = 'APPROVED';

-- 각 월별 총 거래 금액을 계산하고, 거래 금액이 10,000 이상인 달만 출력
SELECT SUM(AMOUNT) AS TOTAL_AMOUNT, TO_CHAR(TRANSACTION_DATE, 'YYYY-MM') AS MONTH
FROM TRANSACTIONS
GROUP BY TO_CHAR(TRANSACTION_DATE, 'YYYY-MM')
HAVING SUM(AMOUNT) >= 10000;

-- 각 지점에서 승인된 대출(APPROVED)의 평균 대출 금액과 총 대출 금액을 계산
SELECT BRANCH_ID, AVG(AMOUNT) AVG_AMOUNT, SUM(AMOUNT) TOTAL_AMOUNT
FROM LOANS
WHERE STATUS = 'APPROVED'
GROUP BY BRANCH_ID
ORDER BY BRANCH_ID;
